
language: ruby
rvm:
  #- 1.8.7 # no, since it doesn't get fun(a, *b, c) or fun0\n.fun1
  #- 1.9.3 # ARGH, Travis no friend
  #- 2.1.1
  - 2.2.2
  - 2.3.1
  - 2.4.1
  #- jruby-19mode # ARGH, Travis no friend
  #- jruby-20mode # ARGH, Travis no friend
script: bundle exec rspec
branches:
  only:
    - master
  #except:
  #  - master

sudo: false
cache: bundler

